project:
  type: book

book:
  title: "Authoring Books with Quarto"
  author: "Anand Chitipothu"
  date: "11/2/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - book-structure.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt



